name: Free space

permissions:
  packages: write
  contents: write

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  cleanup:
    name: Free space
    runs-on: ubuntu-latest
    steps:
      - name: Free some disk space
        run: |
          df -h
          sudo apt-get purge -y '^dotnet-.*' '^llvm-.*' 'php.*' '^mongodb-.*' '^mysql-.*' '^postgresql-.*' '^gfortran-.*' '^cmake-.*' '^aspnetcore-.*' '^clang-.*' '^cpp-.*' '^libmono-.*' '^mono-.*' '^ruby.*' '^r-.*' '^python3-.*' '^temurin-.*' '^java-.*' '^linux-modules-.*' '^libllvm.*' 'x11.*' microsoft-edge-stable azure-cli google-chrome-stable firefox powershell humanity-icon-theme perl-modules-5.34 vim-runtime
          sudo dpkg -P google-cloud-sdk
          sudo rm -rf /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL /usr/local/graalvm/ /usr/local/share/powershell /usr/local/lib/android /usr/local/lib/node_modules /usr/local/.ghcup/ /usr/share/dotnet/ /opt/hostedtoolcache /opt/microsoft /usr/local/aws-* /usr/share/miniconda /opt/az /usr/share/kotlinc /usr/share/man /usr/share/sbt /usr/local/julia1.9.3
          sudo apt-get autoremove -y
          sudo apt-get clean
          sudo rm -rf /var/lib/apt/lists/*
          docker rmi -f node:14 node:16 node:18 node:14-alpine node:16-alpine node:18-alpine ubuntu:18.04 ubuntu:20.04 ubuntu:22.04 debian:10 debian:11 buildpack-deps:buster buildpack-deps:bullseye
          df -h

      - name: Gather information
        run: |
          du -chs /opt/*
          du -chs /usr/*
          du -chs /usr/share/*
          du -chs /usr/local/*
          docker images
          apt list --installed

      - name: List remaining packages
        run: |
          dpkg-query -W --showformat='${Installed-Size;10}\t${Package}\n' | sort  -k1,1n

          sudo apt-get purge -y
          sudo apt-get autoremove -y
          sudo apt-get clean
          df -h
