name: System info

permissions:
  packages: write
  contents: write

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  info:
    name: Get info
    runs-on: ubuntu-latest
    steps:
      - name: Free some disk space
        run: |
          mount
          cat /proc/swaps
          swapon -s

      - name: Get context
        run: |
          echo "`pwd` -> `ls`"
          echo ".. -> `ls ..`"
          echo "../.. -> `ls ../..`"

      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          build-mount-path: /home/runner/work/map-data/storage
          temp-reserve-mb: 10240

      - name: Post maximize
        run: |
          mount
          df -h

          echo "Trying do remove /mnt"
          sudo swapoff -a
          echo "Init pvmove on `sudo losetup -j /mnt/tmp-pv.img |cut -d ':' -f 1`"
          sudo pvmove `sudo losetup -j /mnt/tmp-pv.img |cut -d ':' -f 1` || true
          echo "Init vgreduce on `sudo losetup -j /mnt/tmp-pv.img |cut -d ':' -f 1`"
          sudo vgreduce buildvg `sudo losetup -j /mnt/tmp-pv.img |cut -d ':' -f 1` || true
          sudo resize2fs /dev/mapper/buildvg-buildlv
          sudo mkswap "/dev/mapper/${VG_NAME}-swap"
          sudo swapon "/dev/mapper/${VG_NAME}-swap"

          mount
          df -h


      - name: Test umount
        run: |
          mount

          # Undo volume mounts
          sudo swapoff -a
          sudo umount -f /home/runner/work/map-data/storage
          sudo lvchange -an /dev/mapper/buildvg-swap
          sudo lvchange -an /dev/mapper/buildvg-buildlv
          sudo lvremove -f /dev/mapper/buildvg-swap
          sudo lvremove -f /dev/mapper/buildvg-buildlv
          sudo vgremove buildvg

          echo "lo pv.img"
          sudo losetup -j /pv.img
          echo "lo tmp-pv.img"
          sudo losetup -j /mnt/tmp-pv.img

          echo "Running pvremove"
          sudo pvremove `sudo losetup -j /pv.img |cut -d ':' -f 1`
          sudo pvremove `sudo losetup -j /mnt/tmp-pv.img |cut -d ':' -f 1`
          echo "Running losetup"
          sudo losetup -d `sudo losetup -j /pv.img |cut -d ':' -f 1`
          sudo losetup -d `sudo losetup -j /mnt/tmp-pv.img |cut -d ':' -f 1`

          sudo rm -f /pv.img /mnt/tmp-pv.img
          # Recreate swap
          sudo fallocate -l 4G /mnt/swapfile
          sudo mkswap /mnt/swapfile
          sudo swapon /mnt/swapfile

          mount
          df -h
